mod components;
mod embedded;
mod inputs;
mod outputs;

use crate::widgets::node::Node;

use super::model::WidgetDef;

pub(super) fn compile_widget(def: WidgetDef) -> Result<Node, String> {
    match def {
        WidgetDef::TextOutput { id, text } => Ok(outputs::compile_text_output(id, text)),
        WidgetDef::UrlOutput { id, url, name } => outputs::compile_url_output(id, url, name),
        WidgetDef::ThinkingOutput {
            id,
            label,
            text,
            mode,
            tail_len,
            tick_ms,
            base_rgb,
            peak_rgb,
        } => outputs::compile_thinking_output(
            id, label, text, mode, tail_len, tick_ms, base_rgb, peak_rgb,
        ),
        WidgetDef::ProgressOutput {
            id,
            label,
            min,
            max,
            unit,
            bar_width,
            style,
            transition,
        } => outputs::compile_progress_output(
            id, label, min, max, unit, bar_width, style, transition,
        ),
        WidgetDef::ChartOutput {
            id,
            label,
            mode,
            capacity,
            min,
            max,
            unit,
            gradient,
        } => outputs::compile_chart_output(id, label, mode, capacity, min, max, unit, gradient),
        WidgetDef::TableOutput {
            id,
            label,
            style,
            headers,
            rows,
        } => outputs::compile_table_output(id, label, style, headers, rows),
        WidgetDef::DiffOutput {
            id,
            label,
            old,
            new,
            max_visible,
        } => outputs::compile_diff_output(id, label, old, new, max_visible),
        WidgetDef::TaskLogOutput {
            id,
            visible_lines,
            spinner_style,
            steps,
        } => outputs::compile_task_log_output(id, visible_lines, spinner_style, steps),
        WidgetDef::TextInput {
            id,
            label,
            placeholder,
            default,
            mode,
            required,
            validators,
            completion_items,
            submit_target,
            change_targets,
        } => inputs::compile_text_input(
            id,
            label,
            placeholder,
            default,
            mode,
            required,
            validators,
            completion_items,
            submit_target,
            change_targets,
        ),
        WidgetDef::ArrayInput {
            id,
            label,
            items,
            required,
            validators,
        } => inputs::compile_array_input(id, label, items, required, validators),
        WidgetDef::ButtonInput {
            id,
            label,
            text,
            task_id,
        } => inputs::compile_button_input(id, label, text, task_id),
        WidgetDef::Select {
            id,
            label,
            options,
            selected,
            default,
            required,
            validators,
            submit_target,
        } => inputs::compile_select_input(
            id,
            label,
            options,
            selected,
            default,
            required,
            validators,
            submit_target,
        ),
        WidgetDef::ChoiceInput {
            id,
            label,
            options,
            bullets,
            default,
            required,
            validators,
            submit_target,
        } => inputs::compile_choice_input(
            id,
            label,
            options,
            bullets,
            default,
            required,
            validators,
            submit_target,
        ),
        WidgetDef::SelectList {
            id,
            label,
            options,
            mode,
            max_visible,
            selected,
            show_label,
            submit_target,
        } => components::compile_select_list(
            id,
            label,
            options,
            mode,
            max_visible,
            selected,
            show_label,
            submit_target,
        ),
        WidgetDef::MaskedInput {
            id,
            label,
            mask,
            default,
            required,
            validators,
            submit_target,
        } => inputs::compile_masked_input(
            id,
            label,
            mask,
            default,
            required,
            validators,
            submit_target,
        ),
        WidgetDef::Slider {
            id,
            label,
            min,
            max,
            step,
            unit,
            track_len,
            default,
            required,
            validators,
            change_targets,
        } => inputs::compile_slider_input(
            id,
            label,
            min,
            max,
            step,
            unit,
            track_len,
            default,
            required,
            validators,
            change_targets,
        ),
        WidgetDef::ColorInput {
            id,
            label,
            rgb,
            required,
            validators,
            submit_target,
        } => inputs::compile_color_input(id, label, rgb, required, validators, submit_target),
        WidgetDef::ConfirmInput {
            id,
            label,
            mode,
            yes_label,
            no_label,
            default,
        } => inputs::compile_confirm_input(id, label, mode, yes_label, no_label, default),
        WidgetDef::Checkbox {
            id,
            label,
            checked,
            required,
            validators,
        } => inputs::compile_checkbox_input(id, label, checked, required, validators),
        WidgetDef::Calendar {
            id,
            label,
            mode,
            required,
            validators,
            submit_target,
        } => components::compile_calendar(id, label, mode, required, validators, submit_target),
        WidgetDef::Textarea {
            id,
            min_height,
            max_height,
            default,
            required,
            validators,
        } => {
            components::compile_textarea(id, min_height, max_height, default, required, validators)
        }
        WidgetDef::CommandRunner {
            id,
            label,
            run_mode,
            on_error,
            advance_on_success,
            visible_lines,
            spinner_style,
            timeout_ms,
            commands,
        } => components::compile_command_runner(
            id,
            label,
            run_mode,
            on_error,
            advance_on_success,
            visible_lines,
            spinner_style,
            timeout_ms,
            commands,
        ),
        WidgetDef::FileBrowser {
            id,
            label,
            browser_mode,
            display_mode,
            cwd,
            recursive,
            hide_hidden,
            ext_filter,
            max_visible,
            submit_target,
            required,
            validators,
        } => components::compile_file_browser(
            id,
            label,
            browser_mode,
            display_mode,
            cwd,
            recursive,
            hide_hidden,
            ext_filter,
            max_visible,
            submit_target,
            required,
            validators,
        ),
        WidgetDef::TreeView {
            id,
            label,
            nodes,
            max_visible,
            show_label,
            indent_guides,
            submit_target,
        } => components::compile_tree_view(
            id,
            label,
            nodes,
            max_visible,
            show_label,
            indent_guides,
            submit_target,
        ),
        WidgetDef::ObjectEditor {
            id,
            label,
            value,
            max_visible,
            submit_target,
        } => components::compile_object_editor(id, label, value, max_visible, submit_target),
        WidgetDef::Snippet {
            id,
            label,
            template,
            inputs,
            submit_target,
        } => components::compile_snippet(id, label, template, inputs, submit_target),
        WidgetDef::Table {
            id,
            label,
            style,
            row_numbers,
            initial_rows,
            columns,
        } => components::compile_table(id, label, style, row_numbers, initial_rows, columns),
        WidgetDef::Repeater {
            id,
            label,
            layout,
            show_label,
            show_progress,
            header_template,
            item_label_path,
            items,
            submit_target,
            fields,
        } => components::compile_repeater(
            id,
            label,
            layout,
            show_label,
            show_progress,
            header_template,
            item_label_path,
            items,
            submit_target,
            fields,
        ),
    }
}
